### ISSUE TITLE
Problem using  template tags

### ISSUE THREAD

**Issue by IrishGussy** [dfunckt/django-rules#23] opened 2015-06-03 09:52 UTC
I am having difficulty using template tags in my templates. For example this works

In the view:

```python
from __future__                 import absolute_import
import rules
...
def detail(request, slug):
    obj = get_object_or_404(NewsStory, slug=slug)
    return render(request, 'news/detail.html', {
        'story': obj,
        'can_publish_newsstory': rules.has_perm('can_publish_newsstory', request.user)
        })
```

In the template
```html
       {% if can_publish_newsstory %}
	    <li><a href="{% url 'news:edit' story.slug %}" class="button expand secondary">Edit Story</a></li>
	    <li><a href="{% url 'news:delete' story.slug %}" class="button expand secondary">Delete Story</a></li>
        {% endif %}
```

If I change this to remove  'can_publish_newsstory' from the view and include it in the template, nothing shows.

Revised Template

```html
{% load rules %}
{% has_perm 'can_publish_newsstory' user as can_publish_newsstory %}
       {% if can_publish_newsstory %}
	    <li><a href="{% url 'news:edit' story.slug %}" class="button expand secondary">Edit Story</a></li>
	    <li><a href="{% url 'news:delete' story.slug %}" class="button expand secondary">Delete Story</a></li>
        {% endif %}
```

I am using Python 2.

**Comment by dfunckt** [comment] 2015-06-03 09:57
Hi IrishGussy, could you post your predicate for the "can_publish_newsstory" rule?

**Comment by dfunckt** [comment] 2015-06-03 10:00
Also, have you checked that the "user" variable in your template is correct (eg. is it a valid User instance?)

**Comment by IrishGussy** [comment] 2015-06-03 10:06
The User is a valid User Instance. I can show {{ user.ID}} etc.

Predicate and Rule.

```python
from __future__ import absolute_import
from news.models import NewsStory
from xxx.models import XXX
from django.contrib.auth.models import User
import rules

@rules.predicate
def is_xxx_admin(user):
    return XXX.has_role(user, 'xxx_admin')

rules.add_perm('can_publish_newsstory', is_xxx_admin)
```

In my INSTALLED_APPS, I have 'rules.apps.AutodiscoverRulesConfig' but not 'rules'. Is the rules application necessary for django to pick up the template tag?

**Comment by dfunckt** [comment] 2015-06-03 10:14
No, ``rules`` must be omitted if you're using app configs -- you've got it right.

As a suggestion to verify that there's no issue with XXX.has_role, replace your predicate with rules.always_true, that is:

```
#rules.add_perm('can_publish_newsstory', is_xxx_admin)
rules.add_perm('can_publish_newsstory', rules.always_true)
```

**Comment by IrishGussy** [comment] 2015-06-03 10:18
Just tried that now. No change.

**Comment by dfunckt** [comment] 2015-06-03 10:25
Ok, last suggestion I can think of: have you added rules' ``ObjectPermissionBackend`` in your auth backends setting? See [Checking for permission](https://github.com/dfunckt/django-rules/blob/master/README.rst#checking-for-permission) in README for details.

**Comment by IrishGussy** [comment] 2015-06-03 10:28
Yes. It looks like this.

```Python
AUTHENTICATION_BACKENDS = (
    'rules.permissions.ObjectPermissionBackend',
    'django.contrib.auth.backends.ModelBackend',
)
```

**Comment by dfunckt** [comment] 2015-06-03 10:32
It's weird that it works in the view, and not in the template. The only difference is the checking for permissions in the template goes through Django.

One more suggestion is to add a print statement in [permissions.py:L28](https://github.com/dfunckt/django-rules/blob/master/rules/permissions.py#L28) to make sure that Django doesn't append an app label in front of the permission name -- that is, asking for ``newsstories.can_publish_newsstory`` instead of plain ``can_publish_newsstory``

**Comment by IrishGussy** [comment] 2015-06-03 10:50
I don't believe it is getting to that line. I tried debugging. On running the server, it gets to permissions.py:L27. When I load the page, it gets to templatetags/rules.py:L:15. It never gets to templatetags/rules.py:L:16 nor to permissions.py:L28.

**Comment by dfunckt** [comment] 2015-06-03 11:03
I created a new test project to reproduce the issue, but I couldn't, it just works. Could you provide me with a stripped down test project for me to debug?

**Comment by IrishGussy** [comment] 2015-06-03 11:06
Thanks, leave it with me. I will see what I can do about replicating on a new project or stripping down.

**Comment by dfunckt** [comment] 2015-06-03 11:13
I'm closing the issue for now. If you get a test project together or you find it's even remotely related to rules please feel free to reopen and post back.

**Closed by dfunckt** 2015-06-03 11:13 UTC

**Comment by cfra** [comment] 2020-03-29 19:20
I was pulling out my hair over a problem which appears very similar to the one described here.

In my case, the problem was caused by using the `has_perm` template tag outside of a `block`.

While this parses without any warnings, the tag will never be called and its return value is not available in the scope where it is needed.

I was able to resolve it like this:

```diff
--- a/apps/example/templates/example/thing_frobnicate.html
+++ b/apps/example/templates/example/thing_frobnicate.html
@@ -6,11 +6,10 @@
 {% load thumbnail %}
 {% load wagtailcore_tags %}
 
-{% has_perm 'example.frobnicate_thing' user thing as frobnication_is_authorized %}
-
 {% block body_class %}frobnication-info{% endblock %}
 
 {% block content %}
+   {% has_perm 'example.frobnicate_thing' user thing as frobnication_is_authorized %}
    <div class="pageheader">
        {% if frobnication_is_authorized %}
```

Posting this in the hopes that it might help others to avoid debugging the template tag for multiple hours.
